### PR TITLE
Use HAVE_NC_SET_LOG_LEVEL to determine usage of nc_set_log_level

### LINKED ISSUE #161: Fails to build with netcdf 4.9.3
I'm working on updating netcdf to 4.9.3 in Fedora.  netcdf-cxx4 4.3.1 fails to build with:
```
libtool: link: g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,pack-relative-relocs -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -o .libs/pres_temp_4D_plugin_rd pres_temp_4D_plugin_rd.o  ../cxx4/.libs/libnetcdf_c++4.so -lnetcdf
/usr/bin/ld: /tmp/ccRDJuAl.ltrans0.ltrans.o: in function `main':
/builddir/build/BUILD/netcdf-cxx4-4.3.1-build/netcdf-cxx4-4.3.1/build/examples/../../examples/pres_temp_4D_plugin_wr.cpp:74:(.text.startup+0x17b): undefined reference to `nc_set_log_level'
/usr/bin/ld: /builddir/build/BUILD/netcdf-cxx4-4.3.1-build/netcdf-cxx4-4.3.1/build/examples/../../examples/pres_temp_4D_plugin_wr.cpp:106:(.text.startup+0x2dd): undefined reference to `nc_set_log_level'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:722: pres_temp_4D_plugin_wr] Error 1
```

### PR DESCRIPTION
**Pull request by opoplawski**
fixes #161

### CODE REVIEW

**Comment by opoplawski** [comment]
Can this be merged, or are there issue with this patch?

**Comment by WardF** [comment]
Thanks for the ping!

**Comment by thebaptiste** [comment]
Do you intend to release with this fix (and all other fixes since 4.3.1) ?

**Comment by WardF** [comment]
Yes. This software is clearly lagging far behind, but when we get the next maintenance release of the C library out, I intend a sprint to get the Fortran and C++ interface libraries released as well.

**Comment by ZedThree** [comment]
@WardF I'd be very happy to help get the Fortran and C++ interfaces out -- feel free to get in touch if you want to discuss, my email is on my profile
